# Generated by Django 2.0.3 on 2018-04-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Image', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Route_contains_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Point')),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route')),
            ],
        ),
    ]
