# Generated by Django 2.0.5 on 2018-05-13 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Point_Date', models.DateField(default=datetime.date(2018, 5, 13))),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Image', models.CharField(max_length=150)),
                ('Sound', models.CharField(max_length=33)),
                ('LastUpdate', models.BigIntegerField(default=1526227664398)),
            ],
        ),
        migrations.CreateModel(
            name='Point_Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_Date', models.DateField(default=datetime.date(2018, 5, 13))),
                ('Point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.CharField(max_length=150)),
                ('Map_image', models.CharField(max_length=1000)),
                ('Route_Date', models.DateField(default=datetime.date(2018, 5, 13))),
                ('LastUpdate', models.BigIntegerField(default=1526227664397)),
                ('Number_Downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route_contains_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Point')),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route')),
            ],
        ),
        migrations.CreateModel(
            name='User_Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=150)),
                ('Favorite_points', models.ManyToManyField(to='app.Point')),
                ('Favorite_routes', models.ManyToManyField(to='app.Route')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Visited_points', models.ManyToManyField(to='app.Point_Visited')),
            ],
        ),
        migrations.CreateModel(
            name='User_Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
