# Generated by Django 2.0.3 on 2018-04-26 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='LastUpdate',
            field=models.BigIntegerField(default=1524755567902),
        ),
        migrations.AddField(
            model_name='point',
            name='Point_Date',
            field=models.DateField(default=datetime.date(2018, 4, 26)),
        ),
        migrations.AddField(
            model_name='point',
            name='Sound',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AddField(
            model_name='route',
            name='LastUpdate',
            field=models.BigIntegerField(default=1524755567901),
        ),
        migrations.AddField(
            model_name='route',
            name='Number_Downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='Route_Date',
            field=models.DateField(default=datetime.date(2018, 4, 26)),
        ),
        migrations.AlterField(
            model_name='point',
            name='Image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='route',
            name='Image',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='user_attributes',
            name='Favorite_points',
            field=models.ManyToManyField(to='app.Point'),
        ),
        migrations.AddField(
            model_name='user_attributes',
            name='Favorite_route',
            field=models.ManyToManyField(to='app.Route'),
        ),
    ]
