# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_contains_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Point')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route')),
            ],
        ),
    ]
