# Generated by Django 2.0.3 on 2018-04-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180427_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='LastUpdate',
            field=models.BigIntegerField(default=1525077475747),
        ),
        migrations.AlterField(
            model_name='point',
            name='Point_Date',
            field=models.DateField(default=datetime.date(2018, 4, 30)),
        ),
        migrations.AlterField(
            model_name='route',
            name='LastUpdate',
            field=models.BigIntegerField(default=1525077475745),
        ),
        migrations.AlterField(
            model_name='route',
            name='Route_Date',
            field=models.DateField(default=datetime.date(2018, 4, 30)),
        ),
    ]
