# Generated by Django 2.0.3 on 2018-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180425_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='LastUpdate',
            field=models.BigIntegerField(default=1524683432499),
        ),
        migrations.AlterField(
            model_name='route',
            name='LastUpdate',
            field=models.BigIntegerField(default=1524683432498),
        ),
        migrations.AlterField(
            model_name='user_attributes',
            name='Image',
            field=models.CharField(max_length=150),
        ),
    ]
